<ips:template parameters="$client, $scope" />
<p>{lang="perm_request_prefix"} {$client['client_name']} {lang="perm_request_suffix"}</p>
<p>{lang="perm_list_prefix"}</p>
<ul>
{{foreach $scope as $foo => $perm}}
  <li>{lang="scope_{$perm}"}</li>
{{endforeach}}
</ul>
<form method="post">
    <button name="authorized" class="input_submit" value="Yes" type="submit">{lang="authorize_yes"}</button>
    <button name="authorized" class="input_submit ipsButton_secondary" value="No">{lang="authorize_no"}</button>
    <input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}" />
</form>
