<ips:template parameters="$client" />
<p>Do you authorize the application {$client['client_name']} to login using your credentials?</p>
<form method="post">
    <input type="submit" class="input_submit" name="authorized" value="Yes" />
    <input type="submit" class="input_submit ipsButton_secondary" name="authorized" value="No" />
    <input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}" />
</form>
