<?php

$lang = array(
	'__app_oauth2server'	=> "OAuth2 Server",
    'module__oauth2server_client' => "Applications (OAuth2 Clients)",
    'r__clients' => "Clients",
    'r__clients_manage' => "Can manage clients?",
    'menu__oauth2server_oauthserver' => "OAuth2 Server",
    'menu__oauth2server_oauthserver_clients' => "Applications",
    'add_client' => "Add Application",
    'client_name' => "Application Name",
    'client_name_desc' => "Name of the OAuth2 Application (Client)",
    'redirect_uri' => "Redirect URI",
    'redirect_uri_desc' => "Your application's callback URL or redirect URI",
    'scope' => "Allowed access scope(s)",
    'scope_desc' => "Check to allow the OAuth Application access to the specified type of information. Checked items will also act as default scope if one is not specified.",
    'scope_user.profile' => "User profile information",
    'scope_user.email' => "User email address",
    'scope_user.groups' => "User primary and secondary groups",
    'scope_user.reputation' => "User reputation points",
    'client_id' => "Client ID",
    'client_secret' => "Client Secret",
    'authorization_url' => "Authorization URL",
    'access_token_url' => "Access Token URL",
    'profile_url' => "Profile URL",
    'perm_oauth2server_perm__label' => "Application Permissions",
    'perm_oauth2server_perm__access' => "Access Application",
    'task__expiretokens' => "Expires obsolete access tokens, refresh tokens and authorization codes.",
    'perm_request_prefix' => "Do you authorize the application",
    'perm_request_suffix' => "to access this site?",
    'perm_list_prefix' => "The following access permissions will be granted to the application:"
);
